services:
    php:
        image: bitnamilegacy/php-fpm:latest
        ports:
            - 9000:9000
        volumes:
            - .:/app
    apache:
        image: bitnamilegacy/apache:latest
        ports:
            - 80:8080
        volumes:
            - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
            - .:/app
        depends_on:
            - php
    mariadb:
        image: docker.io/bitnamilegacy/mariadb:10.6
        environment:
            - MARIADB_ROOT_PASSWORD=bitnami
        volumes:
            - "mariadb_data:/bitnami"
    phpmyadmin:
        image: docker.io/bitnamilegacy/phpmyadmin:5
        ports:
            - "8000:8080"
        depends_on:
            - mariadb

volumes:
    mariadb_data:
        driver: local
